const fs = require('fs');
const path = require('path');

function parseMarkdown(content) {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!frontmatterMatch) return null;

  const frontmatter = frontmatterMatch[1];
  const body = frontmatterMatch[2].trim();

  const data = {};
  frontmatter.split('\n').forEach(line => {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) return;
    const key = line.slice(0, colonIndex).trim();
    let value = line.slice(colonIndex + 1).trim();
    // Remove surrounding quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    // Handle tags list (- item format)
    data[key] = value;
  });

  // Parse multiline tags (yaml list format)
  const tagsMatch = frontmatter.match(/tags:\s*\n((?:\s*-\s*.+\n?)+)/);
  if (tagsMatch) {
    data.tags = tagsMatch[1]
      .split('\n')
      .map(l => l.replace(/^\s*-\s*/, '').trim())
      .filter(Boolean);
  } else if (data.tags && typeof data.tags === 'string') {
    // inline list like: tags: [one, two]
    data.tags = data.tags.replace(/[\[\]]/g, '').split(',').map(t => t.trim()).filter(Boolean);
  }

  data.body = body;
  return data;
}

function loadCollection(folder) {
  const dirPath = path.join(__dirname, folder);
  if (!fs.existsSync(dirPath)) {
    console.log(`Folder not found: ${folder} — skipping`);
    return [];
  }

  const files = fs.readdirSync(dirPath).filter(f => f.endsWith('.md'));
  const items = [];

  files.forEach(file => {
    const content = fs.readFileSync(path.join(dirPath, file), 'utf8');
    const parsed = parseMarkdown(content);
    if (!parsed) {
      console.warn(`Skipping ${file} — could not parse frontmatter`);
      return;
    }
    parsed.slug = file.replace(/\.md$/, '');
    items.push(parsed);
  });

  // Sort newest first
  items.sort((a, b) => new Date(b.date) - new Date(a.date));
  return items;
}

const blogs = loadCollection('_posts/blog');
const research = loadCollection('_posts/research');

const output = `// AUTO-GENERATED by build.js — DO NOT EDIT MANUALLY
// Generated: ${new Date().toISOString()}

window.BLOGS = ${JSON.stringify(blogs, null, 2)};

window.RESEARCH = ${JSON.stringify(research, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'content-data.js'), output, 'utf8');

console.log(`✅ content-data.js generated — ${blogs.length} blog post(s), ${research.length} research paper(s)`);
